// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoParaTuTractoCamion.Infrastructure.Persistence;

#nullable disable

namespace TodoParaTuTractoCamion.Infrastructure.Migrations
{
    [DbContext(typeof(TractoCamionDbContext))]
    [Migration("20260322061459_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TodoParaTuTractoCamion.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Imagen1Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imagen2Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Imagen3Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("TodoParaTuTractoCamion.Domain.Entities.Producto", b =>
                {
                    b.OwnsOne("TodoParaTuTractoCamion.Domain.ValueObjects.Precio", "Precio", b1 =>
                        {
                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Precio");

                            b1.HasKey("ProductoId");

                            b1.ToTable("Productos");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.OwnsOne("TodoParaTuTractoCamion.Domain.ValueObjects.Stock", "Stock", b1 =>
                        {
                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("Stock");

                            b1.HasKey("ProductoId");

                            b1.ToTable("Productos");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.Navigation("Precio")
                        .IsRequired();

                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
