// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TodoParaTuTractoCamion.Infrastructure.Persistence;

#nullable disable

namespace TodoParaTuTractoCamion.Infrastructure.Migrations
{
    [DbContext(typeof(TractoCamionDbContext))]
    [Migration("20260324141735_AddDetallesAndCategoria")]
    partial class AddDetallesAndCategoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TodoParaTuTractoCamion.Domain.Entities.Producto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("Detalles")
                        .HasColumnType("text")
                        .HasColumnName("detalles");

                    b.Property<string>("Imagen1Url")
                        .HasColumnType("text")
                        .HasColumnName("imagen1Url");

                    b.Property<string>("Imagen2Url")
                        .HasColumnType("text")
                        .HasColumnName("imagen2Url");

                    b.Property<string>("Imagen3Url")
                        .HasColumnType("text")
                        .HasColumnName("imagen3Url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("TodoParaTuTractoCamion.Domain.Entities.Producto", b =>
                {
                    b.OwnsOne("TodoParaTuTractoCamion.Domain.ValueObjects.Precio", "Precio", b1 =>
                        {
                            b1.Property<string>("ProductoId")
                                .HasColumnType("text");

                            b1.Property<double>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("double precision")
                                .HasColumnName("precio");

                            b1.HasKey("ProductoId");

                            b1.ToTable("Producto");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.OwnsOne("TodoParaTuTractoCamion.Domain.ValueObjects.Stock", "Stock", b1 =>
                        {
                            b1.Property<string>("ProductoId")
                                .HasColumnType("text");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("stock");

                            b1.HasKey("ProductoId");

                            b1.ToTable("Producto");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.Navigation("Precio")
                        .IsRequired();

                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
