// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoParaTuTractoCamion.Infrastructure.Persistence;

#nullable disable

namespace TodoParaTuTractoCamion.Infrastructure.Migrations
{
    [DbContext(typeof(TractoCamionDbContext))]
    partial class TractoCamionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoParaTuTractoCamion.Domain.Entities.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imagen1Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen2Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen3Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("TodoParaTuTractoCamion.Domain.Entities.Producto", b =>
                {
                    b.OwnsOne("TodoParaTuTractoCamion.Domain.ValueObjects.Precio", "Precio", b1 =>
                        {
                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Precio");

                            b1.HasKey("ProductoId");

                            b1.ToTable("Productos");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.OwnsOne("TodoParaTuTractoCamion.Domain.ValueObjects.Stock", "Stock", b1 =>
                        {
                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Stock");

                            b1.HasKey("ProductoId");

                            b1.ToTable("Productos");

                            b1.WithOwner()
                                .HasForeignKey("ProductoId");
                        });

                    b.Navigation("Precio")
                        .IsRequired();

                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
