name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'

      - name: Publish application
        run: dotnet publish TodoParaTuTractoCamion.BlazorWasm/TodoParaTuTractoCamion.BlazorWasm.csproj -c Release -o release --nologo

      - name: Change base-href
        run: sed -i 's/<base href="\/" \/>/<base href="\/TodoParaTuTractoCamion\/" \/>/g' release/wwwroot/index.html

      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: release/wwwroot
